### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by Sxmurai** [b1nzee/DJSv13-Tutorial-Bot#1]
Don't worry, I'm not here to shittalk and I'm here to give some critical feedback.

1. [Cannot index an integer.](https://github.com/b1nzee/DJSv13-Tutorial-Bot/blob/master/events/messageCreate.js#L48)
![image](https://user-images.githubusercontent.com/57580886/141385797-3634c321-a5dc-4379-96ba-3ac450808afb.png)

This will always return NaN instead of null/undefined (thanks JavaScript). Therefore this function will not function properly.

2. Inconsistent code formatting.

This one is not a big one, as I sometimes do this myself. However, you use curly braces around if statements when there is only one thing being called in the closure. This is fine, but you do not do the same with the rest of them. Some of them are on the same line. You also put curly braces on the same line as a statement but other times on another line? I don't know. Again, this isn't highly important but I just thought I'd point that out. Maybe you could introduce a linter of some sort in a future episode?

3. [This can be shortened](https://github.com/b1nzee/DJSv13-Tutorial-Bot/blob/master/events/messageCreate.js#L7#L10)

Instead of a different variable for each, you can do something like:

```js
const [command, ...args] = message.content.slice(client.prefix.length).trim().split(/ +/g);
const cmd = client.commands.get(command.toLowerCase());
```

We know that calling String.split returns an array of strings, that split every whitespace(s). We can assume that the first index is the command. If it isn't, well `cmd` would be undefined. You already have a check for this so it is fine.

---

Glad to see the series finally continue, but I just thought I'd point a few things out. Also, I see to begin with you published the tutorial code on GitHub. What made you change your mind to publish the tutorial code on GitHub rather than making the watch the video?

**Comment by b1nzee** [comment]
Hello, thank you for the feedback.

1. Didn't actually notice my typo there, the index is meant to be outside of the parenthesis - I will point this out in Episode 4 and do a hotfix for it, this will also be included in the Episode 1 description once I amend the problem in Episode 4.

2. Are you referring to where sometimes I do curly braces and then sometimes I don't? I like to try and keep all the code viewable on the whole screen rather than having to scroll to the side. Not sure if I have mistaken your comment here, so correct me if I am wrong by assuming that.

3. Thank you for the suggestion, this will be taken into consideration.

--

What made me change my mind is the fact it's not really up to me on how a person learns, some people learn in different ways. If people want to just clone the source and not learn, that's on them. It's just giving people an extra choice. Those who don't want to learn will typically click off the video anyway and give up when an error occurs.

Good to see you though somewhere other than a Hosting Bot invoice notification!

**Comment by Sxmurai** [comment]
For number two, yeah. Of course it isn't needed but an enforced code style (like eslint) could help new viewers write clean code throughout their project

I'm also talking about you sometimes do:

```js
if (statement)
{

}
```

and then other times do

```js
const func = (arg) => { 

}
```

The one lined statements are fine, as they're just a return statement or something.

A linter might be useful, and not many people use it. Even something as like eslint or the prettier VSCode extension might do.

And yeah, you too. Hopefully your server is going well aswell.

**Comment by b1nzee** [comment]
Just resolved this issue: https://github.com/b1nzee/DJSv13-Tutorial-Bot/commit/a64a26d582ad6a5a5e2a79192a17e0bd0f2dbc7c
